openstf/stf

doc/DEPLOYMENT.md

A couple of typos in the excellent deployment docs. It may be worth bumping the embedded version number to 1.0.3 or a generic tag such as latest or stable? Using the mock auth provider I'm not able to log in, get 302'd to /undefined. Thanks!

Deployment doc typo

---

doc/DEPLOYMENT.md

With current sample nginx.conf, endpoint such as [/auth/api/v1/mock](https://github.com/openstf/stf/blob/master/lib/units/auth/mock.js#L60) or [/auth/api/v1/ldap](https://github.com/openstf/stf/blob/master/lib/units/auth/ldap.js#L61) will be proxied to stf-app instead of stf-auth server which will cause status 302 with /undefined endpoint.
This is a small fix for above problem.

Fix proxy_path for stf-auth in sample nginx.conf

---

res/app/device-list/icons/device-list-icons-directive.js

Currently, shift-click does not work if click event is made on device icon. This fix will allow to start device remote control on standalone mode even click is made on device icon.

Also allow shift-click standalone mode on device icon

---

res/web_modules/nine-bootstrap/nine-bootstrap.scss

Error was:
```
ERROR in ./~/css-loader!./~/sass-loader!./res/web_modules/nine-bootstrap/nine-bootstrap.scss
Module build failed:
.btn &.disabled,
^
Base-level rules cannot contain the parent-selector-referencing character '&'.
Backtrace:
stdin:395
in /Users/Github/stf/res/web_modules/nine-bootstrap/nine-bootstrap.scss (line 395, column 6)
@ ./res/web_modules/nine-bootstrap/nine-bootstrap.scss 4:14-137
```

Fix scss error on gulp build

---

res/app/control-panes/device-control/device-control.css
res/app/control-panes/device-control/device-control.jade

Without these changes, the dropdown occluded the buttons area:
A few CSS tweaks solves it:
Dropdown functionality works correctly.

Fix portrait/landscape buttons clickable area

---

doc/DEPLOYMENT.md
lib/cli.js
lib/units/auth/saml2.js
package.json

Sample Usage
```bash
stf local --auth-type saml2 \
--auth-options '["--saml-id-provider-entry-point-url", "YOUR_ID_PROVIDER_URL", "--saml-id-provider-issuer", "YOUR_ID_PROVIDER_ISSUER"]'
```

SAML2.0 support for authorisation

---

lib/cli.js
lib/units/auth/mock.js
package.json

This PR will add optional basic authentication in `auth-mock` unit.
**Use Case** 
Many of stf users are still using `auth-mock` in their setup. Ideally they should not be using it. With current `auth-mock`, anyone would be able to use stf who has access to URL.
This optional basic auth will add a minute layer of security. If the admin uses this option, only people who have username and password would be able to see login screen.
**Usage**
```bash
BASIC_AUTH_USERNAME=hogehoge BASIC_AUTH_PASSWORD=fogefoge stf local --auth-options '["--use-basic-auth"]'
```

Add optional basic authentication in auth-mock

---

lib/units/provider/index.js

Hi!
When [check()](https://github.com/openstf/stf/blob/master/lib/units/provider/index.js#L304) executed with values `device.present = false` and `willStop = false`:
```node
function check() {
clearTimeout(timer)
if (device.present) {
<...>
}
else {
stop()
}
}
```
from [stop()](https://github.com/openstf/stf/blob/master/lib/units/provider/index.js#L296) started `worker.cancel()`:
```node
function stop() {
if (worker) {
log.info('Shutting down device worker "%s"', device.id)
worker.cancel()
}
}
```
get into [catch(Promise.CancellationError, function()](https://github.com/openstf/stf/blob/master/lib/units/provider/index.js#L250) starting `procutil.gracefullyKill`:
```node
.catch(Promise.CancellationError, function() {
log.info('Gracefully killing device worker "%s"', device.id)
return …
```

Fix worker restart when stopping

---

lib/units/storage/temp.js

`--save-dir` option was there in `storage-temp` unit but it was not being used. Wasn't sure about real intention behind this option. This will give users to save all their uploaded files in a more persistent storage.

Save uploaded files in optional --save-dir directory

---

lib/db/api.js
lib/units/api/controllers/user.js
lib/units/device/plugins/group.js
lib/units/processor/index.js
lib/units/websocket/index.js
lib/wire/wire.proto
res/app/components/stf/device/device-info-filter/index.js
res/app/components/stf/device/enhance-device/enhance-device-service.js
res/app/components/stf/device/state-classes-service.js
res/app/components/stf/keys/add-adb-key/add-adb-key-directive.js
res/app/components/stf/keys/add-adb-key/add-adb-key.css
res/app/components/stf/keys/add-adb-key/add-adb-key.pug
res/app/components/stf/user/user-service.js
res/app/device-list/column/device-column-service.js
res/app/device-list/icons/device-list-icons-directive.js

User will see `Stop Automation` label for devices accessed using API instead of `Stop Using`

Use automation label in device list for devices accessed using API

---

lib/cli/auth-oauth2/index.js
lib/units/auth/oauth2/index.js

This PR adds ability to specify domain of authorized email addresses.
If option is not set then behavior is not changed and any (excluding missing) email address is authorized.
In case of not authorized domain (including missing email address) simple error message is shown.
This theoretically also fixes bug with infinite redirect loop in case of missing email address in response from OAuth provider. At least with Google, unconditional redirect to `/auth/oauth/` used to cause such loop, not sure if email can be missing despite `email` scope is requested and if infinite loop was also applicable to other providers.

Optional email domain restriction added for OAuth2 authorization.

---

doc/DEPLOYMENT.md

Hello,
The docs describing the initial rethinkdb setup were out of date, causing confusion ( see #524 )
I've updated the deployment doc to fix it.

update RethinkDB initial configuration docs

---

lib/util/devutil.js

Seems we intended to filter header line in the output of "ps comm",  it's supposed to initialize flag variable "header" to true.

Initialize flag variable "header" to true in /lib/util/devutil.js

---

lib/util/devutil.js

There exists an incompatibility problem as the shell command "ps comm" is invalid in some devices such as Google Pixel.
Below is the output when I issued "ps com" in Pixel:
sailfish:/ $ ps com
bad pid 'com'
sailfish:/ $ echo $?
1
So I replaced "ps comm" with "ps" which is workable for all the Android device.

replace "ps comm" with "ps" in  the function listPidsByComm

---

doc/API.md
lib/units/api/swagger/api_v1.yaml
lib/units/api/swagger/api_v1_generated.json

@vbanthia 
I took a stab at https://github.com/openstf/stf/issues/594
Appears to address the issue.

Fixes 594 -- Allows default content-type (application/octet-stream) on path based parameter operations

---

res/app/components/stf/screen/screen-directive.js

Issue: https://github.com/openstf/stf/issues/184
The reason of the bug was, on saving screenshot download dialogue will comeup and it will call window.onbeforeunload event.
Currently, `onbeforeunload` is calling `stop` function which is closing webscoket connection. Due to this screen is freezing.

Fix https://github.com/openstf/stf/issues/184

---

CHANGELOG.md
lib/cli/storage-s3/index.js
lib/cli/storage-temp/index.js
lib/units/storage/s3.js
lib/units/storage/temp.js
package.json
yarn.lock

As per #826, the newest version of formidable [changes](https://github.com/felixge/node-formidable/commit/b81d1c71cd3774419571c360db4312c965a57a13) the default maximum file size to 2MB, which is way too low for anything. Make the limit configurable and set to 1GB by default.

Fix formidable's new default maximum file size.

---

lib/db/api.js
lib/units/device/plugins/solo.js
lib/util/devutil.js
lib/wire/wire.proto
res/app/device-list/column/device-column-service.js
res/app/device-list/device-list-controller.js

Sometimes apps requires a device having some minimal OpenGL ES version. This PR adds corresponding column in device list and field in API.
Version is always in format: `<major>.<minor>`. If undefined it falls back to `0.0` to be consistent with [GL_ES_VERSION_UNDEFINED](https://developer.android.com/reference/android/content/pm/FeatureInfo.html#GL_ES_VERSION_UNDEFINED) and to be always parsable as a float.

Add OpenGL ES version to device properties.

---

lib/wire/util.js
lib/wire/wire.proto

The latest version of ADB introduced 2 new device status: connecting and authorizing
See https://github.com/aosp-mirror/platform_system_core/commit/704494b0707a49e064b63192619a73336c1be05a
Without these states, devices sometimes have a problem getting registered with STF.  The error that's encountered is something along the lines of:
```
Jul 13 15:00:36 stf run.sh[2109]: Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
Jul 13 15:00:36 stf run.sh[2109]:     at Field.<anonymous> (/home/tapjoy/.nvm/versions/node/v7.8.0/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
Jul 13 15:00:36 stf run.sh[2109]:     at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue …
```

Support new connecting and authorizing device states from ADB

---

lib/units/device/plugins/screen/stream.js
lib/util/devutil.js

Since Android 8.0 official version, 'ps' command is not workable to list process list. We should use 'ps -lef' instead on Android 8.0 and Android 8.1, so I attempt to fix the problem in lib/util/devutil.js.

Use 'ps -lef' instead of 'ps' to list Pids on Android 8.x

---

README.md

The old link was relative to the repo's root (/blob/master), not to GitHub's project page. This commit fixes the link

docs: Fix relative link to GitHub's contributor's page

---

doc/DEPLOYMENT.md

The SAML authentication example works great, but has a minor typo in the SSL cert mount path.

Fix SAML_ID_PROVIDER_CERT_PATH in example SAML auth provider unit

---

lib/units/api/controllers/user.js
lib/units/api/index.js
lib/units/api/swagger/api_v1.yaml
package.json

Reason: manually approve adb connection from web UI does not scale for test automation. Especially those that are using different adb keys on each session (eg: via container)
This changes also added swagger doc endpoint. Using `stf local` command, it will end up at: `http://localhost:7106/docs/`

Implements addAdbPublicKey API endpoint

---

lib/cli/doctor/index.js

Sometimes the process exits before the data is read from stdout. The result is that the `call` method exits before it has it's output.
Example bug: https://github.com/openstf/stf/issues/1091

Fix for stdout race condition in stf doctor

---

lib/units/device/plugins/service.js

Android prevents the launch of a service if the app is in
background. This change is related to
https://github.com/openstf/STFService.apk/pull/38
which increased the targetSdkLevel of the STFService app
and provides Android 10 support

ensure we are using the relevant command to start the service

---

lib/units/api/swagger/api_v1.yaml

Using API, Group dates have to be provided in UTC conforming to RFC 3339 section 5.6

Update description of Group API in swagger file

---

doc/DEPLOYMENT.md

For playing with STF API against your STF platform using swagger UI tool through a web access, NGINX version is upgraded to 1.17.4

Add swagger UI support in DEPLOYMENT.md

---

lib/units/websocket/index.js

https://github.com/openstf/stf/issues/1180
Multiple touch by using like MicroSoft Surface or Tablets causes a  touchMove error.
The error makes stf service down.
In order to avoid service down, catch the error.
```
/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641
throw Error("Illegal value for "+this.toString(true)+" of type "+this.type.name+": "+val+" ("+msg+")");
^
Error: Illegal value for Message.Field .TouchMoveMessage.contact of type uint32: undefined (not an integer)
at Field.<anonymous> (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2675:29)
at MessagePrototype.set …
```

Catch a touchMove error

---

Dockerfile-debian-armhf

docker buildx tool would produce an error `Error: could not get uid/gid, [ 'nobody', 0 ]` when cross-compiling (I'm not sure if this happened on an actual arm device, I didn't try).
After adding this npm configuration, the build succeeds (after 40 minutes!).
The full error was:
```+ npm install -g npm
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
Error: could not get uid/gid
[ 'nobody', 0 ]
at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
at ChildProcess.exithandler (child_process.js:280:5)
at ChildProcess.emit (events.js:180:13)
at maybeClose (internal/child_process.js:936:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
TypeError: Cannot read property 'get' of undefined
at errorHandler …
```

[armhf] address npm 'could not get uid/gid' error when building with docker buildx for cross-compiling

---

package.json

STF requires Node.js v8.x.
But as you can see from the release note, node-sass v3.4.2 no longer provides the binary built for Node.js v8.x.
https://github.com/sass/node-sass/releases/tag/v3.4.2
```
21:16:10   Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
21:16:11   Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 
21:16:11  
21:16:11   HTTP error 404 Not Found
21:16:11  
21:16:11   Hint: If github.com is not accessible in your location
21:16:11         try setting a proxy via HTTP_PROXY, e.g. 
21:16:11  
21:16:11         export HTTP_PROXY=http://example.com:1234
21:16:11  
21:16:11   or configure npm proxy via
21:16:11  
21:16:11         npm config set proxy …
```

Updates node-sass to v4.13.1
